// frontend/src/app/(auth)/pending-approval/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Alert } from '@/components/ui/alert'
import { useAuth } from '@/store/auth-store'


function PendingApprovalPage() {
  const router = useRouter()
  const { user, refreshUser } = useAuth()
  
  const [isLoading, setIsLoading] = useState(false)
  const [lastChecked, setLastChecked] = useState<Date>(new Date())
  const [autoRefresh, setAutoRefresh] = useState(true)

  // Auto refresh every 30 seconds
  useEffect(() => {
    if (!autoRefresh) return

    const interval = setInterval(async () => {
      await checkApprovalStatus()
    }, 30000)

    return () => clearInterval(interval)
  }, [autoRefresh])

  // Redirect if user is already approved
  useEffect(() => {
    if (user?.primary_role !== 'new_user' && user?.is_active) {
      router.push('/admin')
    }
  }, [user, router])

  const checkApprovalStatus = async () => {
    if (!user) return

    setIsLoading(true)
    try {
      await refreshUser()
      setLastChecked(new Date())
    } catch (error) {
      console.error('Error checking approval status:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleContactSupport = () => {
    const subject = encodeURIComponent('استفسار حول حالة الطلب')
    const body = encodeURIComponent(`
مرحباً فريق Depth Studio،

أرسلت طلب انضمام للمنصة ولكن لم أحصل على رد بعد. 

معلومات حسابي:
- البريد الإلكتروني: ${user?.email}
- تاريخ التقديم: ${user?.created_at}
- الدور المطلوب: ${user?.primary_role}

يرجى مراجعة طلبي والرد في أقرب وقت ممكن.

شكراً لكم
    `)
    
    window.location.href = `mailto:support@depthstudio.com?subject=${subject}&body=${body}`
  }

  const getStatusInfo = () => {
    if (!user) return { status: 'unknown', message: 'خطأ في جلب بيانات المستخدم' }

    switch (user.primary_role) {
      case 'new_user':
        return {
          status: 'pending',
          message: 'طلبك قيد المراجعة',
          description: 'سيتم مراجعة طلبك من قبل المدير العام خلال 24-48 ساعة'
        }
      case 'photographer':
      case 'brand_coordinator':
      case 'marketing_coordinator':
        if (user.is_active) {
          return {
            status: 'approved',
            message: 'تم قبول طلبك!',
            description: 'مرحباً بك في Depth Studio'
          }
        } else {
          return {
            status: 'reviewing',
            message: 'طلبك قيد المراجعة النهائية',
            description: 'يتم الآن تجهيز حسابك، سيتم التفعيل قريباً'
          }
        }
      default:
        return {
          status: 'unknown',
          message: 'حالة غير معروفة',
          description: 'يرجى التواصل مع الدعم'
        }
    }
  }

  const getProgressSteps = () => {
    const baseSteps = [
      { id: 1, title: 'إرسال الطلب', completed: true },
      { id: 2, title: 'مراجعة البيانات', completed: user?.primary_role !== 'new_user' },
      { id: 3, title: 'الموافقة النهائية', completed: user?.is_active === true },
      { id: 4, title: 'تفعيل الحساب', completed: user?.is_active === true }
    ]

    return baseSteps
  }

  const statusInfo = getStatusInfo()
  const progressSteps = getProgressSteps()
  const currentStep = progressSteps.findIndex(step => !step.completed) + 1 || progressSteps.length + 1

  if (!user) {
    router.push('/login')
    return null
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-50 py-8 px-4">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-orange-500 text-white rounded-2xl mb-4">
            <span className="text-3xl">⏳</span>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            {statusInfo.message}
          </h1>
          <p className="text-gray-600">
            {statusInfo.description}
          </p>
        </div>

        {/* Status Alert */}
        {statusInfo.status === 'approved' && (
          <Alert 
            variant="success" 
            message="تهانينا! تم قبول طلبك بنجاح"
            className="mb-6"
          />
        )}

        {/* Progress Steps */}
        <Card className="p-6 mb-6">
          <h3 className="text-lg font-bold text-gray-900 mb-4">مراحل معالجة الطلب</h3>
          
          <div className="space-y-4">
            {progressSteps.map((step) => (
              <div key={step.id} className="flex items-center">
                <div className={`flex items-center justify-center w-8 h-8 rounded-full border-2 ${
                  step.completed 
                    ? 'bg-green-500 border-green-500 text-white'
                    : currentStep === step.id
                    ? 'bg-orange-500 border-orange-500 text-white animate-pulse'
                    : 'bg-gray-100 border-gray-300 text-gray-500'
                }`}>
                  {step.completed ? '✓' : step.id}
                </div>
                
                <div className="mr-4 flex-1">
                  <div className={`font-medium ${
                    step.completed 
                      ? 'text-green-700'
                      : currentStep === step.id
                      ? 'text-orange-700'
                      : 'text-gray-500'
                  }`}>
                    {step.title}
                  </div>
                </div>
                
                {step.completed && (
                  <div className="text-green-500 text-sm">
                    مكتمل
                  </div>
                )}
                
                {currentStep === step.id && (
                  <div className="text-orange-500 text-sm animate-pulse">
                    جاري المعالجة...
                  </div>
                )}
              </div>
            ))}
          </div>
        </Card>

        {/* User Info */}
        <Card className="p-6 mb-6">
          <h3 className="text-lg font-bold text-gray-900 mb-4">معلومات الطلب</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="text-sm text-gray-600">الاسم</label>
              <p className="font-medium">{user.display_name}</p>
            </div>
            
            <div>
              <label className="text-sm text-gray-600">البريد الإلكتروني</label>
              <p className="font-medium">{user.email}</p>
            </div>
            
            <div>
              <label className="text-sm text-gray-600">الدور المطلوب</label>
              <p className="font-medium">
                {user.primary_role === 'photographer' && 'مصور'}
                {user.primary_role === 'brand_coordinator' && 'منسق براند'}
                {user.primary_role === 'marketing_coordinator' && 'منسق تسويق'}
                {user.primary_role === 'new_user' && 'لم يتم التحديد بعد'}
              </p>
            </div>
            
            <div>
              <label className="text-sm text-gray-600">تاريخ التقديم</label>
              <p className="font-medium">
                {user.created_at ? new Date(user.created_at._seconds * 1000).toLocaleDateString('ar-EG') : 'غير محدد'}
              </p>
            </div>
          </div>
        </Card>

        {/* Actions */}
        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row gap-4">
            <Button 
              onClick={checkApprovalStatus}
              disabled={isLoading}
              className="flex-1"
            >
              {isLoading ? 'جاري التحقق...' : 'تحديث الحالة'}
            </Button>
            
            <Button 
              variant="outline"
              onClick={handleContactSupport}
              className="flex-1"
            >
              التواصل مع الدعم
            </Button>
          </div>

          <div className="flex items-center justify-between text-sm text-gray-500">
            <label className="flex items-center">
              <input
                type="checkbox"
                checked={autoRefresh}
                onChange={(e) => setAutoRefresh(e.target.checked)}
                className="ml-2 rounded border-gray-300 text-primary-600"
              />
              تحديث تلقائي كل 30 ثانية
            </label>
            
            <span>
              آخر تحديث: {lastChecked.toLocaleTimeString('ar-EG')}
            </span>
          </div>
        </div>

        {/* Expected Timeline */}
        <Card className="p-6 mt-6 bg-blue-50 border-blue-200">
          <h3 className="text-lg font-bold text-blue-900 mb-2">المدة المتوقعة للمراجعة</h3>
          <div className="space-y-2 text-blue-800">
            <p>• <strong>المصور:</strong> 24-48 ساعة</p>
            <p>• <strong>منسق براند:</strong> 2-3 أيام عمل</p>
            <p>• <strong>منسق تسويق:</strong> 3-5 أيام عمل</p>
          </div>
          <p className="text-sm text-blue-600 mt-3">
            💡 <strong>نصيحة:</strong> تأكد من توفر رقم هاتف صحيح لتسهيل التواصل معك
          </p>
        </Card>

        {/* Back to Home */}
        <div className="text-center mt-8">
          <Link href="/" className="text-primary-600 hover:text-primary-700 font-medium">
            ← العودة للصفحة الرئيسية
          </Link>
        </div>
      </div>
    </div>
  )
}

// Dynamic export to prevent SSR issues
import dynamic from 'next/dynamic'
export default dynamic(() => Promise.resolve(PendingApprovalPage), { ssr: false })

// frontend/src/views/auth/PendingApproval.vue
<template>
  <div class="text-center">
    <div class="mb-6">
      <div class="approval-icon">⏰</div>
      <h2 class="text-xl font-semibold mb-2">طلبك قيد المراجعة</h2>
      <p class="text-gray-600">يرجى انتظار موافقة الإدارة على دورك المطلوب</p>
    </div>
    
    <!-- تفاصيل الطلب -->
    <div class="approval-info mb-6">
      <div class="info-item">
        <span class="label">الدور المطلوب:</span>
        <span class="value">{{ roleDisplayName }}</span>
      </div>
      <div class="info-item">
        <span class="label">تاريخ التقديم:</span>
        <span class="value">{{ submissionDate }}</span>
      </div>
      <div class="info-item">
        <span class="label">البريد الإلكتروني:</span>
        <span class="value">{{ userEmail }}</span>
      </div>
    </div>
    
    <!-- معلومات الوقت -->
    <div class="timeline-card mb-6">
      <h3 class="card-title">الوقت المتوقع للمراجعة</h3>
      <div class="time-estimate">24-48 ساعة</div>
      <p class="time-details">تتم مراجعة الطلبات خلال أيام العمل (الأحد - الخميس)</p>
    </div>
    
    <!-- أزرار العمل -->
    <div class="action-buttons">
      <BaseButton 
        variant="outline"
        @click="refreshStatus"
        :loading="isRefreshing"
        class="mb-3"
      >
        🔄 تحديث الحالة
      </BaseButton>
      
      <BaseButton 
        variant="outline"
        @click="contactSupport"
        class="mb-3"
      >
        📞 تواصل مع الدعم
      </BaseButton>
      
      <BaseButton 
        variant="outline"
        @click="logout"
      >
        🚪 تسجيل خروج
      </BaseButton>
    </div>
    
    <!-- رسالة حالة -->
    <div v-if="statusMessage" class="mt-4 p-3 rounded" :class="statusClass">
      {{ statusMessage }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { BaseButton } from '@/components/common'

const router = useRouter()
const authStore = useAuthStore()

const isRefreshing = ref(false)
const statusMessage = ref('')
const statusType = ref<'success' | 'error' | 'info'>('info')

const userProfile = computed(() => authStore.userProfile)
const userEmail = computed(() => authStore.user?.email || '')

const roleDisplayName = computed(() => {
  const role = userProfile.value?.primary_role
  const roleNames = {
    photographer: 'مصور',
    brand_coordinator: 'منسق براند',
    marketing_coordinator: 'منسق تسويق'
  }
  return roleNames[role as keyof typeof roleNames] || 'غير محدد'
})

const submissionDate = computed(() => {
  const createdAt = userProfile.value?.created_at
  if (!createdAt) return 'غير متوفر'
  
  try {
    // التعامل مع Firebase Timestamp
    const date = createdAt.toDate ? createdAt.toDate() : new Date()
    return date.toLocaleDateString('ar-IQ', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  } catch {
    return 'غير متوفر'
  }
})

const statusClass = computed(() => {
  return {
    'bg-green-100 border border-green-400 text-green-700': statusType.value === 'success',
    'bg-red-100 border border-red-400 text-red-700': statusType.value === 'error',
    'bg-blue-100 border border-blue-400 text-blue-700': statusType.value === 'info'
  }
})

async function refreshStatus() {
  isRefreshing.value = true
  statusMessage.value = ''
  
  try {
    // محاكاة تحديث الحالة
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    // في التطبيق الحقيقي سيتم تحميل ملف المستخدم من قاعدة البيانات
    if (authStore.user?.uid) {
      await authStore.loadUserProfile(authStore.user.uid)
    }
    
    // فحص حالة الموافقة من is_verified بدلاً من status
    const user = authStore.userProfile
    if (user?.is_verified) {
      statusMessage.value = 'تم الموافقة على طلبك! سيتم توجيهك للوحة التحكم'
      statusType.value = 'success'
      
      setTimeout(() => {
        router.push('/app/dashboard')
      }, 2000)
    } else {
      statusMessage.value = 'لا يزال طلبك قيد المراجعة'
      statusType.value = 'info'
    }
    
  } catch (error) {
    statusMessage.value = 'حدث خطأ في تحديث الحالة'
    statusType.value = 'error'
    console.error('Refresh status error:', error)
  } finally {
    isRefreshing.value = false
  }
}

function contactSupport() {
  window.location.href = 'mailto:support@depthstudio.com'
}

async function logout() {
  await authStore.logout()
  router.push('/auth/login')
}

onMounted(() => {
  // التحقق من وجود المستخدم
  if (!authStore.user) {
    router.push('/auth/login')
    return
  }
  
  // إذا كان معتمد بالفعل، توجيه للوحة التحكم
  if (userProfile.value?.is_verified) {
    router.push('/app/dashboard')
  }
})
</script>

<style scoped>
.approval-icon {
  font-size: 64px;
  margin-bottom: 16px;
}

.approval-info {
  background: #f8fafc;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  padding: 20px;
}

.info-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
  border-bottom: 1px solid #e5e7eb;
}

.info-item:last-child {
  border-bottom: none;
}

.label {
  font-weight: 600;
  color: #374151;
}

.value {
  color: #6b7280;
}

.timeline-card {
  background: #eff6ff;
  border: 1px solid #bfdbfe;
  border-radius: 12px;
  padding: 20px;
}

.card-title {
  font-size: 16px;
  font-weight: 600;
  color: #1e40af;
  margin-bottom: 8px;
}

.time-estimate {
  font-size: 24px;
  font-weight: 700;
  color: #2563eb;
  margin-bottom: 8px;
}

.time-details {
  color: #3730a3;
  font-size: 14px;
}

.action-buttons {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
</style>
