// frontend/src/app/(auth)/phone-login/page.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card } from '@/components/ui/card'
import { Alert } from '@/components/ui/alert'
import { authService } from '@/lib/auth'
import { RecaptchaVerifier, ConfirmationResult } from 'firebase/auth'
import { auth } from '@/lib/firebase'

export default function PhoneLoginPage() {
  const router = useRouter()
  const recaptchaRef = useRef<HTMLDivElement>(null)
  
  const [step, setStep] = useState<'phone' | 'verification'>('phone')
  const [phoneNumber, setPhoneNumber] = useState('')
  const [verificationCode, setVerificationCode] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')
  const [confirmationResult, setConfirmationResult] = useState<ConfirmationResult | null>(null)
  const [recaptchaVerifier, setRecaptchaVerifier] = useState<RecaptchaVerifier | null>(null)
  const [resendTimer, setResendTimer] = useState(0)

  // Initialize reCAPTCHA
  useEffect(() => {
    if (step === 'phone' && recaptchaRef.current && !recaptchaVerifier) {
      const verifier = new RecaptchaVerifier(auth, recaptchaRef.current, {
        size: 'invisible',
        callback: () => {
          console.log('reCAPTCHA solved')
        },
        'expired-callback': () => {
          setError('انتهت صلاحية التحقق، يرجى المحاولة مرة أخرى')
        }
      })
      setRecaptchaVerifier(verifier)
    }
  }, [step, recaptchaVerifier])

  // Timer for resend
  useEffect(() => {
    let interval: NodeJS.Timeout
    if (resendTimer > 0) {
      interval = setInterval(() => {
        setResendTimer(prev => prev - 1)
      }, 1000)
    }
    return () => clearInterval(interval)
  }, [resendTimer])

  // تنسيق رقم الهاتف العراقي
  const formatIraqiPhone = (value: string) => {
    // إزالة كل شيء عدا الأرقام
    let cleaned = value.replace(/\D/g, '')
    
    // إذا بدأ بـ 0، نزيله
    if (cleaned.startsWith('0')) {
      cleaned = cleaned.substring(1)
    }
    
    // إضافة التنسيق: XXX XXX XXXX
    if (cleaned.length <= 3) return cleaned
    if (cleaned.length <= 6) return `${cleaned.slice(0, 3)} ${cleaned.slice(3)}`
    return `${cleaned.slice(0, 3)} ${cleaned.slice(3, 6)} ${cleaned.slice(6, 10)}`
  }

  const validateIraqiPhone = (phone: string) => {
    // تنظيف الرقم
    const cleaned = phone.replace(/\D/g, '')
    
    // التحقق من طول الرقم (10 أرقام بدون مفتاح البلد)
    if (cleaned.length !== 10) return false
    
    // التحقق من أن الرقم يبدأ بأرقام صحيحة للشبكات العراقية
    const validPrefixes = ['077', '078', '079', '070', '071', '075', '076', '073', '074']
    const prefix = cleaned.substring(0, 3)
    
    return validPrefixes.includes(prefix)
  }

  const handlePhoneChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const formatted = formatIraqiPhone(e.target.value)
    if (formatted.replace(/\D/g, '').length <= 10) {
      setPhoneNumber(formatted)
      setError('')
    }
  }

  const handleSendCode = async () => {
    const cleanedPhone = phoneNumber.replace(/\D/g, '')
    
    if (!validateIraqiPhone(cleanedPhone)) {
      setError('رقم الهاتف غير صالح. يرجى إدخال رقم عراقي صحيح')
      return
    }

    if (!recaptchaVerifier) {
      setError('خطأ في التحقق، يرجى إعادة تحميل الصفحة')
      return
    }

    setIsLoading(true)
    setError('')

    try {
      const fullPhoneNumber = `+964${cleanedPhone}`
      const confirmation = await authService.sendPhoneVerification({
        phoneNumber: fullPhoneNumber,
        recaptchaVerifier
      })
      
      setConfirmationResult(confirmation)
      setStep('verification')
      setResendTimer(60) // دقيقة واحدة
    } catch (err) {
      setError(err instanceof Error ? err.message : 'فشل في إرسال رمز التحقق')
    } finally {
      setIsLoading(false)
    }
  }

  const handleVerifyCode = async () => {
    if (!confirmationResult) {
      setError('خطأ في التحقق، يرجى المحاولة مرة أخرى')
      return
    }

    if (verificationCode.length !== 6) {
      setError('رمز التحقق يجب أن يكون 6 أرقام')
      return
    }

    setIsLoading(true)
    setError('')

    try {
      await authService.verifyPhoneCode(confirmationResult, verificationCode)
      router.push('/admin')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'رمز التحقق غير صحيح')
    } finally {
      setIsLoading(false)
    }
  }

  const handleResendCode = async () => {
    if (resendTimer > 0) return
    
    setResendTimer(60)
    setError('')
    
    try {
      const cleanedPhone = phoneNumber.replace(/\D/g, '')
      const fullPhoneNumber = `+964${cleanedPhone}`
      
      if (recaptchaVerifier) {
        const confirmation = await authService.sendPhoneVerification({
          phoneNumber: fullPhoneNumber,
          recaptchaVerifier
        })
        setConfirmationResult(confirmation)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'فشل في إعادة إرسال الرمز')
      setResendTimer(0)
    }
  }

  const handleBack = () => {
    setStep('phone')
    setVerificationCode('')
    setError('')
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-600 text-white rounded-2xl mb-4">
            <span className="text-2xl">📱</span>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            {step === 'phone' ? 'تسجيل الدخول برقم الهاتف' : 'تأكيد رقم الهاتف'}
          </h1>
          <p className="text-gray-600">
            {step === 'phone' 
              ? 'أدخل رقم هاتفك العراقي لتسجيل الدخول'
              : `تم إرسال رمز التحقق إلى +964 ${phoneNumber}`
            }
          </p>
        </div>

        <Card className="p-6 bg-white/80 backdrop-blur-sm border-0 shadow-xl">
          {/* Error Alert */}
          {error && (
            <Alert 
              variant="error" 
              message={error}
              dismissible
              onDismiss={() => setError('')}
              className="mb-6"
            />
          )}

          {step === 'phone' ? (
            /* Phone Input Step */
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  رقم الهاتف
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                    <span className="text-gray-500 text-sm">964+</span>
                  </div>
                  <Input
                    type="tel"
                    value={phoneNumber}
                    onChange={handlePhoneChange}
                    placeholder="750 123 4567"
                    className="pr-16 text-left direction-ltr"
                    maxLength={13}
                    required
                  />
                </div>
                <div className="mt-2 text-xs text-gray-500">
                  <p>أرقام مدعومة: آسياسيل (077-079)، زين (070-071)، كورك (075)، إيرثلنك (076)</p>
                </div>
              </div>

              <Button 
                onClick={handleSendCode}
                className="w-full" 
                disabled={isLoading || !phoneNumber}
              >
                {isLoading ? 'جاري الإرسال...' : 'إرسال رمز التحقق'}
              </Button>

              {/* reCAPTCHA */}
              <div ref={recaptchaRef}></div>
            </div>
          ) : (
            /* Verification Step */
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  رمز التحقق
                </label>
                <Input
                  type="text"
                  value={verificationCode}
                  onChange={(e) => {
                    const value = e.target.value.replace(/\D/g, '').slice(0, 6)
                    setVerificationCode(value)
                    setError('')
                  }}
                  placeholder="123456"
                  className="text-center text-2xl tracking-widest"
                  maxLength={6}
                  required
                />
                <div className="mt-2 text-xs text-gray-500 text-center">
                  أدخل الرمز المكون من 6 أرقام المرسل إلى هاتفك
                </div>
              </div>

              <div className="flex space-x-4">
                <Button 
                  onClick={handleBack}
                  variant="outline"
                  className="flex-1"
                  disabled={isLoading}
                >
                  تغيير الرقم
                </Button>
                <Button 
                  onClick={handleVerifyCode}
                  className="flex-1" 
                  disabled={isLoading || verificationCode.length !== 6}
                >
                  {isLoading ? 'جاري التحقق...' : 'تأكيد الرمز'}
                </Button>
              </div>

              {/* Resend Code */}
              <div className="text-center">
                {resendTimer > 0 ? (
                  <p className="text-sm text-gray-500">
                    يمكن إعادة الإرسال بعد {resendTimer} ثانية
                  </p>
                ) : (
                  <button
                    onClick={handleResendCode}
                    className="text-sm text-primary-600 hover:text-primary-700 font-medium"
                  >
                    إعادة إرسال الرمز
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="text-center mt-6 pt-4 border-t border-gray-200">
            <span className="text-gray-600">تفضل طريقة أخرى؟ </span>
            <Link href="/login" className="text-primary-600 hover:text-primary-700 font-medium">
              تسجيل دخول بالإيميل
            </Link>
          </div>
        </Card>

        {/* Help */}
        <div className="text-center mt-6">
          <Link href="/help" className="text-sm text-gray-500 hover:text-gray-700">
            تحتاج مساعدة؟ تواصل معنا
          </Link>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/auth/PhoneLogin.vue
<template>
  <div class="phone-login-container">
    <!-- Header -->
    <div class="text-center mb-8">
      <div class="icon-container">
        <div class="phone-icon">📱</div>
      </div>
      <h2 class="page-title">تسجيل دخول سريع</h2>
      <p class="page-subtitle">استخدم رقم هاتفك للدخول بسهولة</p>
    </div>
    
    <!-- Form Card -->
    <div class="form-card">
      <!-- Phone Number Step -->
      <div v-if="step === 'phone'" class="step-container">
        <div class="step-header">
          <div class="step-indicator">
            <span class="step-number active">1</span>
            <div class="step-line"></div>
            <span class="step-number">2</span>
          </div>
          <p class="step-title">أدخل رقم هاتفك</p>
        </div>
        
        <form @submit.prevent="sendCode" class="space-y-5">
          <div class="phone-input-section">
            <label class="input-label">رقم الهاتف العراقي</label>
            <div class="phone-input-container">
              <div class="country-code">
                <span class="flag">🇮🇶</span>
                <span class="code">+964</span>
              </div>
              <input
                v-model="phoneNumber"
                type="tel"
                placeholder="7XX XXX XXXX"
                class="phone-input"
                maxlength="10"
                required
              />
            </div>
            <p class="input-hint">
              أدخل رقمك بدون الصفر الأول (مثال: 7501234567)
            </p>
          </div>
          
          <BaseButton 
            type="submit" 
            :loading="loading" 
            block
            :disabled="!isValidPhone"
            class="submit-btn"
          >
            <span v-if="!loading" class="flex items-center justify-center gap-2">
              <span>إرسال رمز التحقق</span>
              <span class="text-lg">📨</span>
            </span>
          </BaseButton>
        </form>
        
        <div class="step-footer">
          <button 
            @click="$router.push('/auth/login')"
            class="back-link"
          >
            ← العودة للتسجيل بالبريد
          </button>
        </div>
      </div>
      
      <!-- Verification Step -->
      <div v-else-if="step === 'verification'" class="step-container">
        <div class="step-header">
          <div class="step-indicator">
            <span class="step-number completed">✓</span>
            <div class="step-line completed"></div>
            <span class="step-number active">2</span>
          </div>
          <p class="step-title">تأكيد رمز التحقق</p>
          <p class="verification-info">
            تم إرسال رمز لـ <span class="phone-display">+964 {{ phoneNumber }}</span>
          </p>
        </div>
        
        <form @submit.prevent="verifyCode" class="space-y-5">
          <BaseInput
            v-model="verificationCode"
            type="text"
            label="رمز التحقق (6 أرقام)"
            placeholder="123456"
            maxlength="6"
            required
            class="verification-input"
          />
          
          <BaseButton 
            type="submit" 
            :loading="loading" 
            block
            class="submit-btn"
            :disabled="verificationCode.length !== 6"
          >
            <span v-if="!loading" class="flex items-center justify-center gap-2">
              <span>تأكيد وتسجيل الدخول</span>
              <span class="text-lg">🔓</span>
            </span>
          </BaseButton>
        </form>
        
        <div class="verification-actions">
          <button 
            @click="step = 'phone'"
            class="action-link"
          >
            🔄 تغيير رقم الهاتف
          </button>
          
          <button 
            v-if="canResend"
            @click="sendCode"
            class="action-link resend"
          >
            📤 إعادة إرسال الرمز
          </button>
          <span v-else class="resend-timer">
            إعادة الإرسال خلال {{ resendTimer }}s
          </span>
        </div>
      </div>
    </div>
    
    <!-- reCAPTCHA Container (مخفي) -->
    <div id="recaptcha-container" style="display: none;"></div>
    
    <!-- Error Message -->
    <div v-if="error" class="error-card">
      <div class="flex items-center gap-2">
        <span class="text-xl">⚠️</span>
        <span>{{ error }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { BaseInput, BaseButton } from '@/components/common'

const router = useRouter()
const authStore = useAuthStore()

const step = ref<'phone' | 'verification'>('phone')
const phoneNumber = ref('')
const verificationCode = ref('')
const loading = ref(false)
const error = ref('')
const resendTimer = ref(0)
const canResend = ref(true)

let resendInterval: any = null

const isValidPhone = computed(() => {
  // التحقق من رقم الهاتف العراقي
  return /^7[0-9]{9}$/.test(phoneNumber.value)
})

async function sendCode() {
  if (!isValidPhone.value) {
    error.value = 'رقم الهاتف غير صحيح'
    return
  }
  
  loading.value = true
  error.value = ''
  
  try {
    // استخدام Firebase Phone Auth الحقيقي
    const result = await authStore.sendPhoneVerification(`+964${phoneNumber.value}`)
    
    if (result.success) {
      step.value = 'verification'
      startResendTimer()
      console.log('تم إرسال رمز التحقق بنجاح')
    } else {
      error.value = result.error || 'فشل في إرسال رمز التحقق'
    }
    
  } catch (err: any) {
    error.value = 'فشل في إرسال رمز التحقق'
    console.error('Send code error:', err)
  } finally {
    loading.value = false
  }
}

async function verifyCode() {
  if (verificationCode.value.length !== 6) {
    error.value = 'رمز التحقق يجب أن يكون 6 أرقام'
    return
  }
  
  loading.value = true
  error.value = ''
  
  try {
    // استخدام Firebase Phone Auth الحقيقي
    const result = await authStore.verifyPhoneCode(verificationCode.value)
    
    if (result.success) {
      const user = authStore.userProfile
      if (!user?.primary_role) {
        router.push('/auth/role-setup')
      } else {
        // توجيه حسب الدور
        switch (user.primary_role) {
          case 'super_admin':
            router.push('/app/admin')
            break
          case 'marketing_coordinator':
            router.push('/app/tasks')
            break
          case 'brand_coordinator':
            router.push('/app/brand/dashboard')
            break
          case 'photographer':
            router.push('/app/photographer/tasks/current')
            break
          default:
            router.push('/app/dashboard')
        }
      }
    } else {
      error.value = result.error || 'رمز التحقق غير صحيح'
    }
    
  } catch (err: any) {
    error.value = 'رمز التحقق غير صحيح'
    console.error('Verify code error:', err)
  } finally {
    loading.value = false
  }
}

function startResendTimer() {
  canResend.value = false
  resendTimer.value = 60
  
  resendInterval = setInterval(() => {
    resendTimer.value--
    if (resendTimer.value <= 0) {
      canResend.value = true
      clearInterval(resendInterval)
    }
  }, 1000)
}

onMounted(() => {
  // إعداد reCAPTCHA عند تحميل الصفحة
  authStore.setupRecaptcha('recaptcha-container')
})

onUnmounted(() => {
  // تنظيف المؤقت عند مغادرة الصفحة
  if (resendInterval) {
    clearInterval(resendInterval)
  }
})
</script>

<style scoped>
.phone-login-container {
  max-width: 450px;
  margin: 0 auto;
  padding: 0 20px;
}

/* Header */
.icon-container {
  display: flex;
  justify-content: center;
  margin-bottom: 20px;
}

.phone-icon {
  width: 70px;
  height: 70px;
  background: linear-gradient(135deg, #25d366 0%, #128c7e 100%);
  border-radius: 18px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28px;
  box-shadow: 0 8px 25px rgba(37, 211, 102, 0.3);
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.05); }
}

.page-title {
  font-size: 26px;
  font-weight: 700;
  color: #1a202c;
  margin-bottom: 8px;
  background: linear-gradient(135deg, #25d366 0%, #128c7e 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.page-subtitle {
  color: #718096;
  font-size: 16px;
  font-weight: 500;
}

/* Form Card */
.form-card {
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  border-radius: 20px;
  padding: 28px;
  box-shadow: 
    0 20px 25px -5px rgba(0, 0, 0, 0.1),
    0 10px 10px -5px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

/* Step System */
.step-container {
  width: 100%;
}

.step-header {
  text-align: center;
  margin-bottom: 28px;
}

.step-indicator {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 16px;
}

.step-number {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  font-weight: 600;
  background: #e5e7eb;
  color: #9ca3af;
  transition: all 0.3s ease;
}

.step-number.active {
  background: linear-gradient(135deg, #25d366 0%, #128c7e 100%);
  color: white;
  box-shadow: 0 4px 12px rgba(37, 211, 102, 0.3);
}

.step-number.completed {
  background: linear-gradient(135deg, #10b981 0%, #059669 100%);
  color: white;
}

.step-line {
  width: 60px;
  height: 2px;
  background: #e5e7eb;
  margin: 0 12px;
  transition: all 0.3s ease;
}

.step-line.completed {
  background: linear-gradient(90deg, #10b981, #25d366);
}

.step-title {
  font-size: 18px;
  font-weight: 600;
  color: #1f2937;
  margin-bottom: 8px;
}

.verification-info {
  color: #6b7280;
  font-size: 14px;
}

.phone-display {
  font-weight: 600;
  color: #25d366;
}

.space-y-5 > * + * {
  margin-top: 20px;
}

/* Phone Input */
.phone-input-section {
  margin-bottom: 20px;
}

.input-label {
  display: block;
  margin-bottom: 8px;
  font-size: 14px;
  font-weight: 500;
  color: #374151;
}

.phone-input-container {
  display: flex;
  border: 2px solid #e5e7eb;
  border-radius: 12px;
  overflow: hidden;
  transition: border-color 0.3s ease;
}

.phone-input-container:focus-within {
  border-color: #25d366;
  box-shadow: 0 0 0 3px rgba(37, 211, 102, 0.1);
}

.country-code {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  background: #f8fafc;
  border-right: 1px solid #e5e7eb;
  font-weight: 500;
  color: #374151;
}

.flag {
  font-size: 18px;
}

.phone-input {
  flex: 1;
  padding: 12px 16px;
  border: none;
  outline: none;
  font-size: 16px;
  background: white;
}

.input-hint {
  margin-top: 8px;
  font-size: 12px;
  color: #6b7280;
}

/* Submit Button */
.submit-btn {
  background: linear-gradient(135deg, #25d366 0%, #128c7e 100%);
  border: none;
  padding: 16px;
  border-radius: 12px;
  font-weight: 600;
  font-size: 16px;
  color: white;
  transition: all 0.3s ease;
  box-shadow: 0 4px 15px rgba(37, 211, 102, 0.4);
}

.submit-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(37, 211, 102, 0.6);
}

.submit-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none !important;
}

/* Step Footer */
.step-footer {
  text-align: center;
  margin-top: 24px;
}

.back-link {
  color: #6b7280;
  text-decoration: none;
  font-size: 14px;
  transition: color 0.2s;
  border: none;
  background: none;
  cursor: pointer;
}

.back-link:hover {
  color: #25d366;
}

/* Verification Actions */
.verification-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 20px;
  padding-top: 20px;
  border-top: 1px solid #e5e7eb;
}

.action-link {
  color: #25d366;
  text-decoration: none;
  font-size: 14px;
  font-weight: 500;
  transition: all 0.2s;
  border: none;
  background: none;
  cursor: pointer;
}

.action-link:hover {
  color: #128c7e;
  text-decoration: underline;
}

.resend-timer {
  color: #9ca3af;
  font-size: 14px;
}

/* Error Card */
.error-card {
  margin-top: 20px;
  background: rgba(254, 226, 226, 0.9);
  backdrop-filter: blur(10px);
  border: 1px solid #fca5a5;
  color: #dc2626;
  padding: 16px;
  border-radius: 12px;
  font-weight: 500;
}

/* Utilities */
.flex {
  display: flex;
}

.items-center {
  align-items: center;
}

.justify-center {
  justify-content: center;
}

.gap-2 {
  gap: 8px;
}

/* Responsive */
@media (max-width: 640px) {
  .phone-login-container {
    padding: 0 16px;
  }
  
  .form-card {
    padding: 20px 16px;
    border-radius: 16px;
  }
  
  .page-title {
    font-size: 22px;
  }
  
  .phone-icon {
    width: 60px;
    height: 60px;
    font-size: 24px;
  }
  
  .verification-actions {
    flex-direction: column;
    gap: 12px;
  }
}
</style>
