// frontend/src/app/(auth)/register/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card } from '@/components/ui/card'
import { Alert } from '@/components/ui/alert'
import { authService } from '@/lib/auth'
import { FaGoogle, FaEnvelope, FaPhone, FaEye, FaEyeSlash, FaUser } from 'react-icons/fa'

export default function RegisterPage() {
  const router = useRouter()
  
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: ''
  })
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [agreeToTerms, setAgreeToTerms] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    setError('')
  }

  const validateForm = () => {
    if (!formData.firstName || !formData.lastName || !formData.email || !formData.password) {
      setError('يرجى ملء جميع الحقول المطلوبة')
      return false
    }

    if (formData.password !== formData.confirmPassword) {
      setError('كلمات المرور غير متطابقة')
      return false
    }

    if (formData.password.length < 6) {
      setError('كلمة المرور يجب أن تكون 6 أحرف على الأقل')
      return false
    }

    if (!agreeToTerms) {
      setError('يجب الموافقة على الشروط والأحكام')
      return false
    }

    return true
  }

  const handleEmailRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return

    setIsLoading(true)
    setError('')

    try {
      await authService.register({
        email: formData.email,
        password: formData.password,
        firstName: formData.firstName,
        lastName: formData.lastName,
        phoneNumber: formData.phone
      })
      
      // توجيه مباشر للمستخدمين الجدد لإعداد الدور
      router.push('/role-setup')
         } catch (err) {
       setError(err instanceof Error ? err.message : 'فشل في إنشاء الحساب')
    } finally {
      setIsLoading(false)
    }
  }

  const handleGoogleRegister = async () => {
    setIsLoading(true)
    setError('')

    try {
      await authService.signInWithGoogle()
      // توجيه مباشر للمستخدمين الجدد لإعداد الدور
      router.push('/role-setup')
         } catch (err) {
       setError(err instanceof Error ? err.message : 'فشل في التسجيل بـ Google')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-600 text-white rounded-2xl mb-4">
            <span className="text-2xl">✨</span>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            انضم إلينا اليوم
          </h1>
          <p className="text-gray-600">
            أنشئ حسابك وابدأ رحلتك الإبداعية
          </p>
        </div>

        <Card className="p-6 bg-white/80 backdrop-blur-sm border-0 shadow-xl">
          {/* Error Alert */}
          {error && (
            <Alert 
              variant="error" 
              message={error}
              dismissible
              onDismiss={() => setError('')}
              className="mb-6"
            />
          )}

          {/* Registration Form */}
          <form onSubmit={handleEmailRegister} className="space-y-4 mb-6">
            {/* Name Fields */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  الاسم الأول
                </label>
                <div className="relative">
                  <Input
                    type="text"
                    value={formData.firstName}
                    onChange={(e) => handleInputChange('firstName', e.target.value)}
                    placeholder="أحمد"
                    className="pl-10"
                    required
                  />
                  <FaUser className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  الاسم الأخير
                </label>
                <div className="relative">
                  <Input
                    type="text"
                    value={formData.lastName}
                    onChange={(e) => handleInputChange('lastName', e.target.value)}
                    placeholder="علي"
                    className="pl-10"
                    required
                  />
                  <FaUser className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                </div>
              </div>
            </div>

            {/* Contact Fields */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                البريد الإلكتروني
              </label>
              <div className="relative">
                <Input
                  type="email"
                  value={formData.email}
                  onChange={(e) => handleInputChange('email', e.target.value)}
                  placeholder="your@email.com"
                  className="pl-10"
                  required
                />
                <FaEnvelope className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                رقم الهاتف (اختياري)
              </label>
              <div className="relative">
                <Input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => handleInputChange('phone', e.target.value)}
                  placeholder="+964 750 123 4567"
                  className="pl-10"
                />
                <FaPhone className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
              </div>
            </div>

            {/* Password Fields */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                كلمة المرور
              </label>
              <div className="relative">
                <Input
                  type={showPassword ? 'text' : 'password'}
                  value={formData.password}
                  onChange={(e) => handleInputChange('password', e.target.value)}
                  placeholder="••••••••"
                  className="pl-10 pr-10"
                  required
                />
                <FaEyeSlash className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <FaEyeSlash /> : <FaEye />}
                </button>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                تأكيد كلمة المرور
              </label>
              <div className="relative">
                <Input
                  type={showConfirmPassword ? 'text' : 'password'}
                  value={formData.confirmPassword}
                  onChange={(e) => handleInputChange('confirmPassword', e.target.value)}
                  placeholder="••••••••"
                  className="pl-10 pr-10"
                  required
                />
                <FaEyeSlash className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showConfirmPassword ? <FaEyeSlash /> : <FaEye />}
                </button>
              </div>
            </div>

            {/* Terms Agreement */}
            <div className="flex items-start space-x-3">
              <input
                type="checkbox"
                id="terms"
                checked={agreeToTerms}
                onChange={(e) => setAgreeToTerms(e.target.checked)}
                className="mt-1 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                required
              />
              <label htmlFor="terms" className="text-sm text-gray-600">
                أوافق على{' '}
                <Link href="/terms" className="text-primary-600 hover:text-primary-700">
                  الشروط والأحكام
                </Link>
                {' '}و{' '}
                <Link href="/privacy" className="text-primary-600 hover:text-primary-700">
                  سياسة الخصوصية
                </Link>
              </label>
            </div>

            <Button 
              type="submit" 
              className="w-full" 
              disabled={isLoading}
            >
              {isLoading ? 'جاري إنشاء الحساب...' : 'إنشاء الحساب'}
            </Button>
          </form>

          {/* Divider */}
          <div className="relative mb-6">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-gray-200"></div>
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-2 bg-white text-gray-500">أو انضم بـ</span>
            </div>
          </div>

          {/* Social Registration */}
          <div className="space-y-3">
            <Button 
              variant="outline" 
              className="w-full" 
              onClick={handleGoogleRegister}
              disabled={isLoading}
            >
              <FaGoogle className="ml-2 text-red-500" />
              التسجيل بـ Google
            </Button>

            <Button 
              variant="outline" 
              className="w-full"
              onClick={() => router.push('/phone-login')}
            >
              <FaPhone className="ml-2 text-green-500" />
              التسجيل برقم الهاتف
            </Button>
          </div>

          {/* Footer */}
          <div className="text-center mt-6 pt-4 border-t border-gray-200">
            <span className="text-gray-600">لديك حساب بالفعل؟ </span>
            <Link href="/login" className="text-primary-600 hover:text-primary-700 font-medium">
              تسجيل الدخول
            </Link>
          </div>
        </Card>

        {/* Help */}
        <div className="text-center mt-6">
          <Link href="/help" className="text-sm text-gray-500 hover:text-gray-700">
            تحتاج مساعدة؟ تواصل معنا
          </Link>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/auth/Register.vue
<template>
  <div class="register-container">
    <!-- Header -->
    <div class="text-center mb-8">
      <div class="icon-container">
        <div class="register-icon">✨</div>
      </div>
      <h2 class="page-title">انضم إلينا اليوم</h2>
      <p class="page-subtitle">أنشئ حسابك وابدأ رحلتك الإبداعية</p>
    </div>
    
    <!-- Form Card -->
    <div class="form-card">
      <form @submit.prevent="handleSubmit" class="space-y-5">
        <!-- Name Fields -->
        <div class="name-grid">
          <BaseInput
            v-model="firstName"
            type="text"
            label="الاسم الأول"
            placeholder="أحمد"
            required
            class="input-enhanced"
          />
          
          <BaseInput
            v-model="lastName"
            type="text"
            label="الاسم الأخير"
            placeholder="علي"
            required
            class="input-enhanced"
          />
        </div>
        
        <!-- Contact Fields -->
        <BaseInput
          v-model="email"
          type="email"
          label="البريد الإلكتروني"
          placeholder="example@domain.com"
          required
          class="input-enhanced"
        />
        
        <BaseInput
          v-model="phone"
          type="tel"
          label="رقم الهاتف (اختياري)"
          placeholder="+964 750 123 4567"
          class="input-enhanced"
        />
        
        <!-- Password Fields -->
        <BaseInput
          v-model="password"
          type="password"
          label="كلمة المرور"
          placeholder="••••••••"
          required
          class="input-enhanced"
        />
        
        <BaseInput
          v-model="confirmPassword"
          type="password"
          label="تأكيد كلمة المرور"
          placeholder="••••••••"
          required
          class="input-enhanced"
        />
        
        <!-- Terms Agreement -->
        <div class="terms-section">
          <label class="terms-checkbox">
            <input v-model="agreeToTerms" type="checkbox" required class="checkbox-custom">
            <span class="checkmark"></span>
            <span class="terms-text">
              أوافق على 
              <a href="#" class="link-styled">الشروط والأحكام</a>
              و
              <a href="#" class="link-styled">سياسة الخصوصية</a>
            </span>
          </label>
        </div>
        
        <!-- Submit Button -->
        <BaseButton 
          type="submit" 
          :loading="loading" 
          block
          class="submit-btn"
        >
          <span v-if="!loading" class="flex items-center justify-center gap-2">
            <span>إنشاء الحساب</span>
            <span class="text-lg">🚀</span>
          </span>
        </BaseButton>
      </form>
      
      <!-- Divider -->
      <div class="divider-container">
        <div class="divider-line"></div>
        <span class="divider-text">أو انضم بـ</span>
        <div class="divider-line"></div>
      </div>
      
      <!-- Google Registration -->
      <BaseButton 
        variant="outline" 
        block
        @click="handleGoogleRegister"
        :loading="googleLoading"
        class="google-btn"
      >
        <span class="flex items-center justify-center gap-3">
          <span class="text-xl">🔴</span>
          <span>التسجيل بـ Google</span>
        </span>
      </BaseButton>
      
      <!-- Footer -->
      <div class="form-footer">
        <span class="text-gray-600">لديك حساب بالفعل؟ </span>
        <button 
          @click="$router.push('/auth/login')"
          class="link-button"
        >
          تسجيل الدخول
        </button>
      </div>
    </div>
    
    <!-- Error Message -->
    <div v-if="error" class="error-card">
      <div class="flex items-center gap-2">
        <span class="text-xl">⚠️</span>
        <span>{{ error }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { BaseInput, BaseButton } from '@/components/common'

const router = useRouter()
const authStore = useAuthStore()

const firstName = ref('')
const lastName = ref('')
const email = ref('')
const phone = ref('')
const password = ref('')
const confirmPassword = ref('')
const agreeToTerms = ref(false)
const loading = ref(false)
const googleLoading = ref(false)
const error = ref('')

async function handleSubmit() {
  // تحقق من البيانات
  if (!firstName.value || !lastName.value || !email.value || !password.value) {
    error.value = 'يرجى ملء جميع الحقول المطلوبة'
    return
  }
  
  if (password.value !== confirmPassword.value) {
    error.value = 'كلمات المرور غير متطابقة'
    return
  }
  
  if (!agreeToTerms.value) {
    error.value = 'يجب الموافقة على الشروط والأحكام'
    return
  }
  
  loading.value = true
  error.value = ''
  
  try {
    const result = await authStore.register({
      email: email.value,
      password: password.value,
      first_name: firstName.value,
      last_name: lastName.value,
      phone: phone.value,
      primary_role: 'photographer'  // افتراضي، سيتم تغييره في RoleSetup
    })
    
    if (result.success) {
      router.push('/auth/role-setup')
    } else {
      error.value = result.error || 'خطأ في إنشاء الحساب'
    }
  } catch (err: any) {
    error.value = 'خطأ في إنشاء الحساب'
    console.error('Register error:', err)
  } finally {
    loading.value = false
  }
}

async function handleGoogleRegister() {
  if (!agreeToTerms.value) {
    error.value = 'يجب الموافقة على الشروط والأحكام'
    return
  }
  
  googleLoading.value = true
  error.value = ''
  
  try {
    const result = await authStore.loginWithGoogle()
    
    if (result.success) {
      router.push('/auth/role-setup')
    } else {
      error.value = 'فشل التسجيل بـ Google'
    }
  } catch (err: any) {
    error.value = 'فشل التسجيل بـ Google'
    console.error('Google register error:', err)
  } finally {
    googleLoading.value = false
  }
}
</script>

<style scoped>
.register-container {
  max-width: 480px;
  margin: 0 auto;
  padding: 0 20px;
}

/* Header */
.icon-container {
  display: flex;
  justify-content: center;
  margin-bottom: 20px;
}

.register-icon {
  width: 75px;
  height: 75px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 18px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 30px;
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);
  animation: sparkle 2s ease-in-out infinite;
}

@keyframes sparkle {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.05); }
}

.page-title {
  font-size: 26px;
  font-weight: 700;
  color: #1a202c;
  margin-bottom: 8px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.page-subtitle {
  color: #718096;
  font-size: 16px;
  font-weight: 500;
}

/* Form Card */
.form-card {
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  border-radius: 20px;
  padding: 28px;
  box-shadow: 
    0 20px 25px -5px rgba(0, 0, 0, 0.1),
    0 10px 10px -5px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.space-y-5 > * + * {
  margin-top: 20px;
}

/* Name Grid */
.name-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

@media (max-width: 640px) {
  .name-grid {
    grid-template-columns: 1fr;
    gap: 20px;
  }
}

/* Terms Section */
.terms-section {
  padding: 16px;
  background: #f8fafc;
  border-radius: 12px;
  border: 1px solid #e2e8f0;
}

.terms-checkbox {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  cursor: pointer;
  line-height: 1.5;
}

.checkbox-custom {
  position: absolute;
  opacity: 0;
  cursor: pointer;
}

.checkmark {
  position: relative;
  top: 2px;
  height: 20px;
  width: 20px;
  background-color: white;
  border: 2px solid #d1d5db;
  border-radius: 4px;
  transition: all 0.3s ease;
  flex-shrink: 0;
}

.terms-checkbox:hover .checkmark {
  border-color: #667eea;
}

.checkbox-custom:checked ~ .checkmark {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-color: #667eea;
}

.checkmark:after {
  content: "";
  position: absolute;
  display: none;
  left: 6px;
  top: 2px;
  width: 6px;
  height: 10px;
  border: solid white;
  border-width: 0 2px 2px 0;
  transform: rotate(45deg);
}

.checkbox-custom:checked ~ .checkmark:after {
  display: block;
}

.terms-text {
  font-size: 14px;
  color: #4b5563;
}

.link-styled {
  color: #667eea;
  text-decoration: none;
  font-weight: 600;
  transition: color 0.2s;
}

.link-styled:hover {
  color: #764ba2;
  text-decoration: underline;
}

/* Submit Button */
.submit-btn {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
  padding: 16px;
  border-radius: 12px;
  font-weight: 600;
  font-size: 16px;
  color: white;
  transition: all 0.3s ease;
  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
}

.submit-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.6);
}

/* Divider */
.divider-container {
  display: flex;
  align-items: center;
  margin: 28px 0;
}

.divider-line {
  flex: 1;
  height: 1px;
  background: linear-gradient(90deg, transparent, #e2e8f0, transparent);
}

.divider-text {
  padding: 0 16px;
  color: #a0aec0;
  font-size: 14px;
  font-weight: 500;
}

/* Google Button */
.google-btn {
  padding: 14px;
  border-radius: 12px;
  font-weight: 500;
  transition: all 0.3s ease;
  border: 1.5px solid #e2e8f0;
  margin-bottom: 20px;
}

.google-btn:hover {
  border-color: #db4437;
  background: rgba(219, 68, 55, 0.05);
  transform: translateY(-1px);
}

/* Footer */
.form-footer {
  text-align: center;
  font-size: 15px;
}

.link-button {
  color: #667eea;
  font-weight: 600;
  text-decoration: none;
  transition: all 0.2s;
  border: none;
  background: none;
  cursor: pointer;
}

.link-button:hover {
  color: #764ba2;
  text-decoration: underline;
}

/* Error Card */
.error-card {
  margin-top: 20px;
  background: rgba(254, 226, 226, 0.9);
  backdrop-filter: blur(10px);
  border: 1px solid #fca5a5;
  color: #dc2626;
  padding: 16px;
  border-radius: 12px;
  font-weight: 500;
}

/* Utilities */
.flex {
  display: flex;
}

.items-center {
  align-items: center;
}

.justify-center {
  justify-content: center;
}

.gap-2 {
  gap: 8px;
}

.gap-3 {
  gap: 12px;
}

/* Responsive */
@media (max-width: 640px) {
  .register-container {
    padding: 0 16px;
  }
  
  .form-card {
    padding: 20px 16px;
    border-radius: 16px;
  }
  
  .page-title {
    font-size: 22px;
  }
  
  .register-icon {
    width: 60px;
    height: 60px;
    font-size: 24px;
  }
}
</style>
