// frontend/src/views/auth/Login.vue
<template>
  <div class="login-container">
    <!-- Header مع Animation -->
    <div class="text-center mb-8">
      <div class="logo-container">
        <div class="logo-gradient">📸</div>
      </div>
      <h2 class="welcome-title">أهلاً بك مرة أخرى</h2>
      <p class="welcome-subtitle">سجل دخولك للمتابعة</p>
    </div>
    
    <!-- Form Container -->
    <div class="form-card">
      <form @submit.prevent="handleSubmit" class="space-y-5">
        <BaseInput
          v-model="email"
          type="email"
          label="البريد الإلكتروني"
          placeholder="example@domain.com"
          required
          :error="emailError"
          class="input-enhanced"
        />
        
        <BaseInput
          v-model="password"
          type="password"
          label="كلمة المرور"
          placeholder="••••••••"
          required
          :error="passwordError"
          class="input-enhanced"
        />
        
        <!-- Remember & Forgot -->
        <div class="flex justify-between items-center text-sm">
          <label class="flex items-center gap-2 cursor-pointer">
            <input v-model="rememberMe" type="checkbox" class="checkbox-custom">
            <span class="text-gray-600">تذكرني</span>
          </label>
          <a href="#" class="text-blue-600 hover:text-blue-700 transition-colors">
            نسيت كلمة المرور؟
          </a>
        </div>
        
        <BaseButton 
          type="submit" 
          :loading="loading" 
          loadingText="جاري تسجيل الدخول..."
          block
          class="btn-primary-enhanced"
        >
          <span v-if="!loading" class="flex items-center justify-center gap-2">
            <span>تسجيل الدخول</span>
            <span class="text-lg">→</span>
          </span>
        </BaseButton>
      </form>
      
      <!-- Divider -->
      <div class="divider-container">
        <div class="divider-line"></div>
        <span class="divider-text">أو متابعة بـ</span>
        <div class="divider-line"></div>
      </div>
      
      <!-- Social Buttons -->
      <div class="social-buttons">
        <BaseButton 
          variant="outline" 
          block
          @click="handleGoogleLogin"
          :loading="googleLoading"
          class="social-btn google-btn"
        >
          <span class="flex items-center justify-center gap-3">
            <span class="text-xl">🔴</span>
            <span>Google</span>
          </span>
        </BaseButton>
        
        <BaseButton 
          variant="outline" 
          block
          @click="$router.push('/auth/phone-login')"
          class="social-btn phone-btn"
        >
          <span class="flex items-center justify-center gap-3">
            <span class="text-xl">📱</span>
            <span>رقم الهاتف</span>
          </span>
        </BaseButton>
      </div>
      
      <!-- Footer -->
      <div class="form-footer">
        <span class="text-gray-600">ليس لديك حساب؟ </span>
        <button 
          @click="$router.push('/auth/register')"
          class="link-button"
        >
          إنشاء حساب جديد
        </button>
      </div>
    </div>
    
    <!-- Error Message -->
    <div v-if="error" class="error-card">
      <div class="flex items-center gap-2">
        <span class="text-xl">⚠️</span>
        <span>{{ error }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { BaseInput, BaseButton } from '@/components/common'

const router = useRouter()
const authStore = useAuthStore()

const email = ref('')
const password = ref('')
const loading = ref(false)
const googleLoading = ref(false)
const error = ref('')
const rememberMe = ref(false)
const emailError = ref('')
const passwordError = ref('')

// معالجة redirect result عند تحميل الصفحة
onMounted(async () => {
  try {
    const result = await authStore.handleRedirectResult()
    if (result.success) {
      handleSuccessfulAuth()
    }
  } catch (err) {
    console.error('Redirect result error:', err)
  }
})

function handleSuccessfulAuth() {
  const user = authStore.userProfile
  const userRole = user?.primary_role
  
  if (!user?.is_verified) {
    router.push('/auth/pending-approval')
  } else if (!userRole) {
    router.push('/auth/role-setup')
  } else {
    // توجيه حسب الدور
    switch (userRole) {
      case 'super_admin':
        router.push('/app/admin')
        break
      case 'marketing_coordinator':
        router.push('/app/tasks')
        break
      case 'brand_coordinator':
        router.push('/app/brand/dashboard')
        break
      case 'photographer':
        router.push('/app/photographer/tasks/current')
        break
      default:
        router.push('/app/dashboard')
    }
  }
}

async function handleSubmit() {
  // مسح الأخطاء السابقة
  emailError.value = ''
  passwordError.value = ''
  error.value = ''
  
  // التحقق من البيانات
  if (!email.value) {
    emailError.value = 'البريد الإلكتروني مطلوب'
    return
  }
  
  if (!email.value.includes('@')) {
    emailError.value = 'البريد الإلكتروني غير صحيح'
    return
  }
  
  if (!password.value) {
    passwordError.value = 'كلمة المرور مطلوبة'
    return
  }
  
  if (password.value.length < 6) {
    passwordError.value = 'كلمة المرور يجب أن تكون 6 أحرف على الأقل'
    return
  }
  
  loading.value = true
  
  try {
    const result = await authStore.login({
      email: email.value,
      password: password.value,
      remember_me: rememberMe.value
    })
    
    if (result.success) {
      handleSuccessfulAuth()
    } else {
      error.value = result.error || 'خطأ في تسجيل الدخول'
    }
  } catch (err: any) {
    console.error('Login error:', err)
    error.value = 'حدث خطأ غير متوقع، حاول مرة أخرى'
  } finally {
    loading.value = false
  }
}

async function handleGoogleLogin() {
  googleLoading.value = true
  error.value = ''
  
  try {
    const result = await authStore.loginWithGoogle()
    
    if (result.success) {
      if (result.message) {
        // إذا كان redirect، أعطي رسالة للمستخدم
        error.value = result.message
        // سيتم معالجة النتيجة في onMounted
      } else {
        // تم تسجيل الدخول مباشرة
        handleSuccessfulAuth()
      }
    } else {
      error.value = result.error || 'فشل تسجيل الدخول بـ Google'
    }
  } catch (err: any) {
    console.error('Google login error:', err)
    
    // تحسين رسائل الخطأ
    if (err.code === 'auth/popup-blocked') {
      error.value = 'تم حظر النافذة المنبثقة. يرجى السماح للنوافذ المنبثقة وإعادة المحاولة'
    } else if (err.code === 'auth/popup-closed-by-user') {
      error.value = 'تم إلغاء تسجيل الدخول'
    } else {
      error.value = 'فشل تسجيل الدخول بـ Google'
    }
  } finally {
    googleLoading.value = false
  }
}
</script>

<style scoped>
.login-container {
  max-width: 420px;
  margin: 0 auto;
  padding: 0 20px;
}

/* Logo & Header */
.logo-container {
  display: flex;
  justify-content: center;
  margin-bottom: 24px;
}

.logo-gradient {
  width: 80px;
  height: 80px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 32px;
  box-shadow: 0 10px 30px rgba(102, 126, 234, 0.3);
  animation: logoFloat 3s ease-in-out infinite;
}

@keyframes logoFloat {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-10px); }
}

.welcome-title {
  font-size: 28px;
  font-weight: 700;
  color: #1a202c;
  margin-bottom: 8px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.welcome-subtitle {
  color: #718096;
  font-size: 16px;
  font-weight: 500;
}

/* Form Card */
.form-card {
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  border-radius: 24px;
  padding: 32px;
  box-shadow: 
    0 20px 25px -5px rgba(0, 0, 0, 0.1),
    0 10px 10px -5px rgba(0, 0, 0, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.space-y-5 > * + * {
  margin-top: 20px;
}

/* Enhanced Button */
.btn-primary-enhanced {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
  padding: 16px;
  border-radius: 12px;
  font-weight: 600;
  font-size: 16px;
  color: white;
  transition: all 0.3s ease;
  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
}

.btn-primary-enhanced:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.6);
}

/* Custom Checkbox */
.checkbox-custom {
  width: 18px;
  height: 18px;
  border-radius: 4px;
  border: 2px solid #e2e8f0;
  transition: all 0.2s;
}

.checkbox-custom:checked {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-color: #667eea;
}

/* Divider */
.divider-container {
  display: flex;
  align-items: center;
  margin: 32px 0;
}

.divider-line {
  flex: 1;
  height: 1px;
  background: linear-gradient(90deg, transparent, #e2e8f0, transparent);
}

.divider-text {
  padding: 0 16px;
  color: #a0aec0;
  font-size: 14px;
  font-weight: 500;
}

/* Social Buttons */
.social-buttons {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 24px;
}

.social-btn {
  padding: 14px;
  border-radius: 12px;
  font-weight: 500;
  transition: all 0.3s ease;
  border: 1.5px solid #e2e8f0;
}

.google-btn:hover {
  border-color: #db4437;
  background: rgba(219, 68, 55, 0.05);
  transform: translateY(-1px);
}

.phone-btn:hover {
  border-color: #25d366;
  background: rgba(37, 211, 102, 0.05);
  transform: translateY(-1px);
}

/* Footer */
.form-footer {
  text-align: center;
  font-size: 15px;
}

.link-button {
  color: #667eea;
  font-weight: 600;
  text-decoration: none;
  transition: all 0.2s;
  border: none;
  background: none;
  cursor: pointer;
}

.link-button:hover {
  color: #764ba2;
  text-decoration: underline;
}

/* Error Card */
.error-card {
  margin-top: 20px;
  background: rgba(254, 226, 226, 0.9);
  backdrop-filter: blur(10px);
  border: 1px solid #fca5a5;
  color: #dc2626;
  padding: 16px;
  border-radius: 12px;
  font-weight: 500;
}

/* Responsive */
@media (max-width: 480px) {
  .login-container {
    padding: 0 16px;
  }
  
  .form-card {
    padding: 24px 20px;
    border-radius: 16px;
  }
  
  .welcome-title {
    font-size: 24px;
  }
  
  .logo-gradient {
    width: 60px;
    height: 60px;
    font-size: 24px;
  }
}

/* Flex utilities */
.flex {
  display: flex;
}

.items-center {
  align-items: center;
}

.justify-center {
  justify-content: center;
}

.justify-between {
  justify-content: space-between;
}

.gap-2 {
  gap: 8px;
}

.gap-3 {
  gap: 12px;
}
</style>

// frontend/src/app/(auth)/login/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card } from '@/components/ui/card'
import { Alert } from '@/components/ui/alert'
import { useAuth } from '@/store/auth-store'
import { FaGoogle, FaEnvelope, FaPhone, FaEye, FaEyeSlash } from 'react-icons/fa'

export default function LoginPage() {
  const router = useRouter()
  const { login, loginWithGoogle, isLoading, error, clearError, user, isAuthenticated } = useAuth()
  
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [formError, setFormError] = useState('')

  // Auto redirect if already authenticated
  useEffect(() => {
    if (isAuthenticated && user) {
      console.log('🔥 User is authenticated in login page, redirecting to dashboard...', user)
      
      // Redirect based on user role immediately
      let redirectPath = '/admin' // default
      
      switch (user.primary_role) {
        case 'super_admin':
          redirectPath = '/admin'
          break
        case 'marketing_coordinator':
          redirectPath = '/marketing'
          break
        case 'brand_coordinator':
          redirectPath = '/brand'
          break
        case 'photographer':
          redirectPath = '/photographer'
          break
        case 'new_user':
          redirectPath = '/role-setup'
          break
        default:
          redirectPath = '/admin'
      }
      
      // Check status
      if (user.status === 'pending_approval') {
        redirectPath = '/pending-approval'
      }
      
      console.log(`🔄 Login page: Redirecting ${user.primary_role} (${user.status}) to ${redirectPath}`)
      router.push(redirectPath)
    }
  }, [isAuthenticated, user, router])

  const handleEmailLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    clearError()
    setFormError('')

    if (!email || !password) {
      setFormError('يرجى ملء جميع الحقول')
      return
    }

    try {
      await login(email, password)
      // التوجيه بعد تسجيل الدخول الناجح سيتم بواسطة AuthWrapper
    } catch (error) {
      // Show specific error message if Firebase is not available
      if (error instanceof Error && error.message.includes('Firebase')) {
        setFormError('خدمة الاستيثاق غير متاحة حالياً. يرجى المحاولة لاحقاً.')
      } else {
        setFormError('خطأ في تسجيل الدخول. يرجى التحقق من البيانات.')
      }
    }
  }

   const handleGoogleLogin = async () => {
     clearError()
     try {
       console.log('Starting Google login...')
       await loginWithGoogle()
       console.log('Google login successful, AuthWrapper will handle redirect...')
       // التوجيه بعد تسجيل الدخول الناجح سيتم بواسطة AuthWrapper
     } catch (error) {
       console.error('Google login error:', error)
       setFormError('خطأ في تسجيل الدخول بـ Google')
     }
   }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-600 text-white rounded-2xl mb-4">
            <span className="text-2xl">🎯</span>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            مرحباً بعودتك
          </h1>
          <p className="text-gray-600">
            سجل دخولك إلى Depth Studio
          </p>
        </div>

        <Card className="p-6 bg-white/80 backdrop-blur-sm border-0 shadow-xl">
          {/* Error Alert */}
          {(error || formError) && (
            <Alert 
              variant="error" 
              message={error || formError}
              dismissible
              onDismiss={() => {
                clearError()
                setFormError('')
              }}
              className="mb-6"
            />
          )}

          {/* Email Login Form */}
          <form onSubmit={handleEmailLogin} className="space-y-4 mb-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                البريد الإلكتروني
              </label>
              <div className="relative">
                <Input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="your@email.com"
                  className="pl-10"
                  required
                />
                <FaEnvelope className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                كلمة المرور
              </label>
              <div className="relative">
                <Input
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="pl-10 pr-10"
                  required
                />
                <FaEyeSlash className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <FaEyeSlash /> : <FaEye />}
                </button>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <label className="flex items-center">
                <input type="checkbox" className="rounded border-gray-300 text-primary-600 focus:ring-primary-500" />
                <span className="mr-2 text-sm text-gray-600">تذكرني</span>
              </label>
                          <Link href="/reset-password" className="text-sm text-primary-600 hover:text-primary-700">
              نسيت كلمة المرور؟
            </Link>
            </div>

                         <Button 
               type="submit" 
               className="w-full" 
               disabled={isLoading}
             >
               {isLoading ? 'جاري التحميل...' : 'تسجيل الدخول'}
             </Button>
          </form>

          {/* Divider */}
          <div className="relative mb-6">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-gray-200"></div>
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-2 bg-white text-gray-500">أو سجل دخولك بـ</span>
            </div>
          </div>

          {/* Social Login */}
          <div className="space-y-3">
            <Button 
              variant="outline" 
              className="w-full" 
              onClick={handleGoogleLogin}
              disabled={isLoading}
            >
              <FaGoogle className="ml-2 text-red-500" />
              تسجيل الدخول بـ Google
            </Button>

            <Button 
              variant="outline" 
              className="w-full"
              onClick={() => router.push('/phone-login')}
            >
              <FaPhone className="ml-2 text-green-500" />
              تسجيل الدخول برقم الهاتف
            </Button>
          </div>

          {/* Footer */}
          <div className="text-center mt-6 pt-4 border-t border-gray-200">
            <span className="text-gray-600">ليس لديك حساب؟ </span>
            <Link href="/register" className="text-primary-600 hover:text-primary-700 font-medium">
              سجل الآن
            </Link>
          </div>
        </Card>

        {/* Help */}
        <div className="text-center mt-6">
          <Link href="/help" className="text-sm text-gray-500 hover:text-gray-700">
            تحتاج مساعدة؟ تواصل معنا
          </Link>
        </div>
      </div>
    </div>
  )
}
